export const emptyHero = {
  breadcrumb: {
    value: "CONTINENTS / EUROPE",
    textColor: "#d29393",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Unveil the Soul of Europe",
    textColor: "#FFFFFF",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value: "From Ancient Empires to Wild Alpine Horizons",
    textColor: "#E5E7EB",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value: "Immerse yourself in timeless cultural heritage, majestic mountain passes, sun-drenched Mediterranean shores, and secluded storybook villages crafted for discerning explorers.",
    textColor: "#F3F4F6",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  isCenter: false,
  buttons: [
    {
      label: "Explore European Journeys",
      url: "/journeys?continent=europe",
      style: "primary",
      variant: "PRIMARY",
      textColor: "#000000",
      backgroundColor: "#ffffff",
    },
  ],
  backgroundMultimedia: {
    show: "video",
    image: {
      url: "",
      alt: "Panoramic European Alpine Landscape",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Cinematic Aerial View",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    color: {
      color: "#171717",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
  },
}
