export const emptyStats = {
  title: {
    value: "Key Regional Statistics",
    textColor: "#182d09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  items: [
    { label: "Coastline", value: "170 km", description: "Ionian & Adriatic coastline" },
    { label: "Sunshine", value: "300+ Days", description: "Mediterranean sunshine annually" },
    { label: "Water Temp", value: "24–27°C", description: "Peak summer swimming" },
    { label: "Best Access", value: "Vlorë / Sarandë", description: "Coastal highway or ferry" },
    { label: "Beach Season", value: "May – Oct", description: "Peak window: Jun–Sep" },
    { label: "Currency", value: "Albanian Lek / EUR", description: "Cards accepted in towns" },
  ],
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FFFFFF",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Stats background",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Stats background video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
