export const createEmptyMultimediaItem = () => ({
  show: "image" as const,
  color: {
    color: "#FFFFFF",
    opacity: 100,
    width: "100%",
    height: "100%",
    aspectRatio: "auto",
  },
  image: {
    url: null,
    alt: null,
    opacity: 100,
    overlayColor: "#000000",
    overlayOpacity: 0,
    width: "100%",
    height: "auto",
    aspectRatio: "auto",
    fit: "cover" as const,
  },
  video: {
    url: null,
    alt: null,
    opacity: 100,
    overlayColor: "#000000",
    overlayOpacity: 0,
    autoplay: true,
    loop: true,
    muted: true,
    width: "100%",
    height: "auto",
    aspectRatio: "auto",
    fit: "cover" as const,
  },
})

export const emptyPhilosophy = {
  eyebrow: {
    value: "OUR PHILOSOPHY",
    textColor: "#B86B3A",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "We believe the way you travel matters.",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "We believe true luxury lies in unhurried moments and intimate local insight. Every journey is designed specifically around your pace, preferences, and desires.\n\nOur team works closely with each traveler to craft narrative itineraries that balance discovery with rest.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  quote: {
    value: "“Because the most memorable travel experiences are rarely the loudest ones.”",
    textColor: "#B86B3A",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  multimedias: [
    {
      show: "image",
      color: { color: "#FFFFFF", opacity: 100, width: "100%", height: "100%", aspectRatio: "auto" },
      image: {
        url: "https://res.cloudinary.com/dscqp4wwt/image/upload/v1789789105/P/philosophyImage1/mwlarjdjn6k8sg7uiecq.png",
        alt: "Balkan authentic travel",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: null,
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    {
      show: "image",
      color: { color: "#FFFFFF", opacity: 100, width: "100%", height: "100%", aspectRatio: "auto" },
      image: {
        url: "https://res.cloudinary.com/dscqp4wwt/image/upload/v1789789106/P/philosophyImage2/oxbjerskvgzibnudp0iw.jpg",
        alt: "Balkan destination",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: null,
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    {
      show: "image",
      color: { color: "#FFFFFF", opacity: 100, width: "100%", height: "100%", aspectRatio: "auto" },
      image: {
        url: "https://res.cloudinary.com/dscqp4wwt/image/upload/v1789789107/P/philosophyImage3/prkazquiqzr3uv4oln9i.jpg",
        alt: "Balkan scenery",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: null,
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
  ],
  backgroundMultimedia: {
    show: "color",
    color: { color: "#FAF7F2", opacity: 100, width: "100%", height: "100%", aspectRatio: "auto" },
    image: {
      url: null,
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: null,
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
