export const emptyPeopleItem = {
  name: {
    value: "Elena Rostova",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  designation: {
    value: "Founder & Lead Travel Designer",
    textColor: "#B86B3A",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  multimedia: {
    show: "image",
    color: {
      color: "#E5E7EB",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Elena Rostova",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  social: [
    { icon: "linkedin", label: "LinkedIn", url: "https://linkedin.com" },
    { icon: "instagram", label: "Instagram", url: "https://instagram.com" },
  ],
}

export const emptyPeople = {
  eyebrow: {
    value: "THE PEOPLE BEHIND MIRA",
    textColor: "#B86B3A",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Curated by people who know the region intimately.",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "Behind every MIRA journey is a team that spends significant time exploring, refining, and understanding the destinations we offer. We believe expertise comes from presence — from returning to the same places repeatedly and building trusted local relationships.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  members: [
    {
      name: {
        value: "Elena Rostova",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      designation: {
        value: "Founder & Lead Travel Designer",
        textColor: "#B86B3A",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      multimedia: {
        show: "image",
        color: {
          color: "#E5E7EB",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
        image: {
          url: "",
          alt: "Elena Rostova",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: null,
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          autoplay: true,
          loop: true,
          muted: true,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
      },
      social: [
        { icon: "linkedin", label: "LinkedIn", url: "https://linkedin.com" },
        { icon: "instagram", label: "Instagram", url: "https://instagram.com" },
      ],
    },
    {
      name: {
        value: "Marko Petrovic",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      designation: {
        value: "Regional Experience Director",
        textColor: "#B86B3A",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      multimedia: {
        show: "image",
        color: {
          color: "#E5E7EB",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
        image: {
          url: "",
          alt: "Marko Petrovic",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: null,
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          autoplay: true,
          loop: true,
          muted: true,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
      },
      social: [
        { icon: "linkedin", label: "LinkedIn", url: "https://linkedin.com" },
      ],
    },
  ],
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FAF7F2",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
