export const emptyCharacter = {
  label: {
    value: "CHARACTER",
    textColor: "#af6348",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "What makes this region singular",
    textColor: "#182d09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  items: [
    {
      title: {
        value: "Untouched Alpine Wilderness",
        textColor: "#182d09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value: "The Accursed Mountains remained almost entirely off-limits to outsiders until the early 2000s. Today they offer trekking with a frontier quality that the Alps lost generations ago — without the lifts or crowds.",
        textColor: "#565e69",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      href: "/destinations/albania/north-albania/wilderness",
      linkText: "Read More",
      buttons: [
        {
          label: "Read More",
          url: "/destinations/albania/north-albania/wilderness",
          variant: "PRIMARY",
          style: "primary",
          backgroundColor: "#af6348",
          textColor: "#ffffff",
        },
      ],
      multimedia: null,
    },
    {
      title: {
        value: "Living Highland Culture",
        textColor: "#182d09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value: "The Kanun — a 15th-century code of highland law governing hospitality, marriage, and property — is still informally observed in remote villages.",
        textColor: "#565e69",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      href: "/destinations/albania/north-albania/culture",
      linkText: "Read More",
      buttons: [
        {
          label: "Read More",
          url: "/destinations/albania/north-albania/culture",
          variant: "PRIMARY",
          style: "primary",
          backgroundColor: "#af6348",
          textColor: "#ffffff",
        },
      ],
      multimedia: null,
    },
    {
      title: {
        value: "The Great Slow Journeys",
        textColor: "#182d09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value: "The Komani Lake ferry and the Valbona-to-Theth trail have become essential experiences of the northern Balkans. Both remain unhurried and impossible to replicate.",
        textColor: "#565e69",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      href: "/destinations/albania/north-albania/slow-journeys",
      linkText: "Read More",
      buttons: [
        {
          label: "Read More",
          url: "/destinations/albania/north-albania/slow-journeys",
          variant: "PRIMARY",
          style: "primary",
          backgroundColor: "#af6348",
          textColor: "#ffffff",
        },
      ],
      multimedia: null,
    },
  ],
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FFF8F2",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Character Background Pattern",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Character Background Video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
