export const emptyExploreJourneys = {
  eyebrow: {
    value: "Journeys",
    textColor: "#C5A880",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Explore Our Journeys",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value: "Find the journey that matches the way you want to travel.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "A series of intentionally paced journeys designed for those who seek the authentic grain of history, from mountain monasteries to coastal ruins.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FBF9F5",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: null,
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: null,
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  buttons: [
    {
      label: "Explore Journeys",
      url: "/journeys",
      variant: "PRIMARY",
      style: "primary",
      rounded: "full",
      backgroundColor: "#182D09",
      backgroundOpacity: 100,
      textColor: "#ffffff",
      textOpacity: 100,
      hoverBackgroundColor: "#f3f4f6",
      hoverTextColor: "#000000",
      target: "_self",
      showIcon: true,
    },
  ],
}
