export const emptyFaq = {
  title: {
    value: "Frequently Asked Questions",
    textColor: "#182d09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  imageMultimedia: {
    show: "image",
    image: {
      url: "",
      alt: "Frequently Asked Questions",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "100%",
      aspectRatio: "1:1",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    color: {
      color: "#EDE7D8",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "1:1",
    },
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#F8F5EE",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "FAQ Background Pattern",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "FAQ Background Video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  items: [],
}
