export const emptyPracticalInfo = {
  label: {
    value: "PRACTICAL INFORMATION",
    textColor: "#af6348",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Essential Insights Before You Travel",
    textColor: "#182d09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  items: [
    {
      id: "practical-1",
      title: {
        value: "Entry & Visa Requirements",
        textColor: "#182d09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      content: {
        value: "EU citizens and passport holders from over 80 countries can enter visa-free for up to 90 days. Ensure your passport is valid for at least 3 months beyond your planned stay.",
        textColor: "#565e69",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      multimedia: null,
      imageMultimedia: null,
      is_expanded: true,
    },
    {
      id: "practical-2",
      title: {
        value: "Currency & Payment Methods",
        textColor: "#182d09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      content: {
        value: "Local currency is widely accepted alongside Euros in tourist centers. Credit and debit cards are accepted at major hotels and restaurants, though cash is recommended for local markets.",
        textColor: "#565e69",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      multimedia: null,
      imageMultimedia: null,
      is_expanded: false,
    },
    {
      id: "practical-3",
      title: {
        value: "Best Time to Visit & Climate",
        textColor: "#182d09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      content: {
        value: "Spring (May–June) and Autumn (September–October) offer ideal pleasant weather for sightseeing with fewer crowds. Summer is perfect for coastal escapes.",
        textColor: "#565e69",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      multimedia: null,
      imageMultimedia: null,
      is_expanded: false,
    },
  ],
  imageMultimedia: {
    show: "color",
    color: {
      color: "#EDE7D8",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Practical Information Image",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  sideImageMultimedia: {
    show: "color",
    color: {
      color: "#EDE7D8",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Practical Information Image",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FFF8F2",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Practical Info Background Pattern",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Practical Info Background Video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
