export const emptyNewsletterCmsHero = {
  title: {
    value: "A Curated Travel Perspective",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value: "Thoughtful dispatches featuring curated Balkan travel inspiration, MIRA Stories, regional travel insights, and selected journeys.",
    textColor: "#565E69",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  emailLabel: {
    value: "Enter your email address",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  buttonText: "Subscribe",
  inputPlaceholder: "Insert your email here",
  image: {
    url: "",
    alt: "Travelers gathered at a scenic coastal viewpoint",
    fit: "cover",
    width: "100%",
    height: "auto",
    opacity: 100,
  },
  backgroundMultimedia: {
    show: "image",
    color: {
      color: "#FFFFFF",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Travelers gathered at a scenic coastal viewpoint",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
    video: {
      url: "",
      alt: "",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      autoplay: true,
      loop: true,
      muted: true,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
  },
  links: {
    exploreJourneys: {
      label: "Explore journeys",
      url: "/journeys",
    },
    returnHome: {
      label: "Return Home",
      url: "/",
    },
  },
}
