export const emptyCustomJourneyCta = {
  title: {
    value: "Prefer something more personal? Let’s design it together",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "Tell us how you like to travel. We will create a personal journey shaped around your pace, interests, and preferred level of comfort — tailored with intimate local insight down to every unhurried detail.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FBF9F5",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  rightSideMultimedia: {
    show: "image",
    color: {
      color: "#FBF9F5",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Let us design your journey",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  buttons: [
    {
      label: "Plan my journey",
      url: "/plan-your-journey",
      variant: "PRIMARY",
      style: "primary",
      rounded: "full",
      backgroundColor: "#182D09",
      backgroundOpacity: 100,
      textColor: "#ffffff",
      textOpacity: 100,
      hoverBackgroundColor: "#f3f4f6",
      hoverTextColor: "#000000",
      target: "_self",
      showIcon: true,
    },
  ],
}
