export const emptyStaySentenceItem = {
  value: "",
  textColor: "#F3F4F6",
  textOpacity: 1,
  backgroundColor: null,
  backgroundOpacity: 1,
}

export const emptyStay = {
  title: {
    value: "The journeys that stay with us are never only about where we went.",
    textColor: "#F3F4F6",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  items: [
    {
      value: "They are about how a place made us feel.",
      textColor: "#F3F4F6",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    {
      value: "The atmosphere of a quiet coastal village.",
      textColor: "#F3F4F6",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    {
      value: "A conversation shared over dinner.",
      textColor: "#F3F4F6",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    {
      value: "A road through the mountains at sunset.",
      textColor: "#F3F4F6",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    {
      value: "The sense of discovering something genuine and deeply connected to its surroundings.",
      textColor: "#F3F4F6",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
  ],
  closingText: {
    value: "At MIRA, we create journeys designed to leave exactly that feeling behind.",
    textColor: "#B86B3A",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#182D09",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: null,
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
