export const emptyCta = {
  title: {
    value: "Didn't find your perfect journey?",
    textColor: "#182d09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "Our collection is carefully designed but every travel is different.\nIf you'd like something more personal, we'd love to create it together.",
    textColor: "#565e69",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  buttons: [
    {
      label: "Plan a tailor-made journey",
      url: "/contact",
      style: "primary",
      variant: "PRIMARY",
      backgroundColor: "#af6348",
      textColor: "#ffffff",
    },
  ],
  imageMultimedia: {
    show: "image",
    image: {
      url: "",
      alt: "CTA Motif",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
      fit: "contain",
    },
    video: {
      url: "",
      alt: "",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    color: {
      color: "#EDE7D8",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#EDE7D8",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "CTA Background Pattern",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "CTA Background Video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
