export const emptyGallery = {
  badge: {
    value: "Visual Story",
    textColor: "#af6348",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Journey Gallery",
    textColor: "#080c1d",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value: "Immerse yourself in the atmosphere of this destination.",
    textColor: "#565e69",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  items: [
    {
      title: { value: "Albanian Coastline", textColor: "#ffffff", textOpacity: 1, backgroundColor: null, backgroundOpacity: 1 },
      type: "image",
      multimedia: {
        show: "image",
        image: {
          url: "",
          alt: "Albanian Coastline",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: "",
          autoplay: true,
          loop: true,
          muted: true,
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        color: {
          color: "#ffffff",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
      },
    },
    {
      title: { value: "Historic Berat", textColor: "#ffffff", textOpacity: 1, backgroundColor: null, backgroundOpacity: 1 },
      type: "image",
      multimedia: {
        show: "image",
        image: {
          url: "",
          alt: "Historic Berat",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: "",
          autoplay: true,
          loop: true,
          muted: true,
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        color: {
          color: "#ffffff",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
      },
    },
    {
      title: { value: "Ottoman Fortress", textColor: "#ffffff", textOpacity: 1, backgroundColor: null, backgroundOpacity: 1 },
      type: "image",
      multimedia: {
        show: "image",
        image: {
          url: "",
          alt: "Ottoman Fortress",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: "",
          autoplay: true,
          loop: true,
          muted: true,
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        color: {
          color: "#ffffff",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
      },
    },
    {
      title: { value: "Theth Alps", textColor: "#ffffff", textOpacity: 1, backgroundColor: null, backgroundOpacity: 1 },
      type: "image",
      multimedia: {
        show: "image",
        image: {
          url: "",
          alt: "Theth Alps",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: "",
          autoplay: true,
          loop: true,
          muted: true,
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        color: {
          color: "#ffffff",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
      },
    },
    {
      title: { value: "Blue Eye Spring", textColor: "#ffffff", textOpacity: 1, backgroundColor: null, backgroundOpacity: 1 },
      type: "image",
      multimedia: {
        show: "image",
        image: {
          url: "",
          alt: "Blue Eye Spring",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: "",
          autoplay: true,
          loop: true,
          muted: true,
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        color: {
          color: "#ffffff",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
      },
    },
  ],
  backgroundMultimedia: {
    show: "color",
    image: {
      url: "",
      alt: "Gallery Background Image",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Gallery Background Video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    color: {
      color: "#ffffff",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
  },
}
