export const emptyNewsletterCmsUnsubscribe = {
  title: {
    value: "We're Sorry to See You Go",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  unsubscribedTitle: {
    value: "You're Unsubscribed",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value: "If our travel dispatches no longer inspire your adventures, confirm your email below to unsubscribe. You can return at any time.",
    textColor: "#565E69",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  unsubscribedSubtitle: {
    value: "You have been removed from our dispatch list. Our curated stories and journey itineraries remain open whenever you wish to return.",
    textColor: "#565E69",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  reasonsTitle: {
    value: "Help us understand why (optional):",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  reasonsList: [
    "Emails are too frequent",
    "Content is no longer relevant",
    "Taking a break from travel planning",
    "I never signed up for this",
    "Other reasons",
  ],
  leftSideMultimedia: {
    show: "image",
    color: {
      color: "#FFFFFF",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Traveler reflecting on a journey",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
    video: {
      url: "",
      alt: "",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      autoplay: true,
      loop: true,
      muted: true,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FFFFFF",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Background",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
    video: {
      url: "",
      alt: "",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      autoplay: true,
      loop: true,
      muted: true,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
  },
}
