export const emptyItinerary = {
  badge: "Day by Day",
  title: "Crafted Itinerary",
  description: "Detailed daily journey highlights and schedule.",
  chaptersList: [
    {
      id: "chap-1",
      chapterNumber: "Chapter I",
      title: "The Beginning",
      subtitle: "Days 1–3 · Tirana & surroundings",
      description: "Introductory exploration of historic Albanian architecture and culinary culture.",
      days: [
        {
          id: "day-1",
          dayNumber: 1,
          title: "Arrival in Tirana & Welcome Cocktail",
          subtitle: "Private transfer & introductory dinner",
          location: "Tirana",
          description: "Arrive at Tirana airport with private transfer to your boutique hotel. Enjoy an evening welcome cocktail and traditional introductory dinner.",
          stayName: "Plaza Hotel Tirana",
          image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
          meals: ["Dinner"],
          activities: ["Private Transfer", "Welcome Cocktail"],
        },
        {
          id: "day-2",
          dayNumber: 2,
          title: "Historic Berat Castle & Wine Tasting",
          subtitle: "UNESCO fortress grounds",
          location: "Berat",
          description: "Explore the UNESCO listed town of Berat, visit the castle grounds, and enjoy exclusive wine tasting at a family vineyard.",
          stayName: "Mangalem Heritage Hotel",
          image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80",
          meals: ["Breakfast", "Wine Tasting"],
          activities: ["Castle Guided Tour", "Vineyard Walk"],
        },
        {
          id: "day-3",
          dayNumber: 3,
          title: "Gjirokastër Stone City Exploration",
          subtitle: "Ottoman architecture & fortress",
          location: "Gjirokastër",
          description: "Discover Gjirokastër's Ottoman architecture, ancient fortress museum, and artisan craft bazaar.",
          stayName: "Gjirokastër Castle Hotel",
          image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
          meals: ["Breakfast", "Lunch"],
          activities: ["Craft Bazaar Visit", "Fortress Walk"],
        },
      ],
    },
    {
      id: "chap-2",
      chapterNumber: "Chapter II",
      title: "Into the Mountains",
      subtitle: "Days 4–7 · Northern Alps & Valbona",
      description: "Breathtaking mountain passes, pristine alpine valleys, and secluded waterfalls.",
      days: [
        {
          id: "day-4",
          dayNumber: 4,
          title: "Theth National Park & Blue Eye Exploration",
          subtitle: "Alpine springs & isolation tower",
          location: "Theth",
          description: "Journey into the heart of the Albanian Alps. Hike to the natural turquoise Blue Eye spring and visit the traditional lock-in tower.",
          stayName: "Theth Alpine Sanctuary",
          image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
          meals: ["Breakfast", "Dinner"],
          activities: ["Alpine Trekking", "Blue Eye Spring"],
        },
      ],
    },
  ],
  daysList: [],
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FAF6F0",
      opacity: 1,
    },
  },
}
