export const emptyWhyMira = {
  eyebrow: {
    value: "Why MIRA",
    textColor: "#E5A84B",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Travel, shaped by insight. Refined through experience.",
    textColor: "#FFFFFF",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "MIRA exists as a quiet force behind the region's most curated journeys. We are rooted in the authentic Balkan heritage, believing that true exploration requires a deep, editorial understanding of the land's silent narratives. Every expedition is a private monograph, meticulously designed to bridge the gap between contemporary luxury and the raw, untethered spirit of the frontier.\n\nMIRA exists as a quiet force behind the region's most curated journeys. We are rooted in the authentic Balkan heritage, believing that true exploration requires a deep, editorial understanding of the land's silent narratives. Every expedition is a private monograph, meticulously designed to bridge the gap between contemporary luxury and the raw, untethered spirit of the frontier.",
    textColor: "#F3F4F6",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  signature: {
    value: "— MIRA",
    textColor: "#E5A84B",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#182D09",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: null,
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: null,
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  rightSideMultimedia: {
    show: "image",
    color: {
      color: "#182D09",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: null,
      alt: "Why MIRA curated Balkan journey",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: null,
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
