export const emptyTravelInsights = {
  eyebrow: {
    value: "THE EDITORIAL",
    textColor: "#C5A880",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Travel Insights",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value:
      "A collection of personal, cultural and inspiring stories. Each piece offers a deeper view of the Balkans and its people beyond the expected.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "Prepare for your journey with our comprehensive insider guides.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FBF9F5",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  buttons: [
    {
      label: "View All Stories",
      url: "/stories",
      variant: "PRIMARY",
      style: "primary",
      rounded: "full",
      backgroundColor: "#182D09",
      backgroundOpacity: 100,
      textColor: "#ffffff",
      textOpacity: 100,
      hoverBackgroundColor: "#f3f4f6",
      hoverTextColor: "#000000",
      target: "_self",
      showIcon: true,
    },
  ],
}
