export const emptyTravelInsights = {
  eyebrow: {
    value: "THE EDITORIAL",
    textColor: "#C5A880",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Travel Insights",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value:
      "A collection of personal, cultural and inspiring stories. Each piece offers a deeper view of the Balkans and its people beyond the expected.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "Prepare for your journey with our comprehensive insider guides.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FBF9F5",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  leftSideMultimedia: {
    show: "image",
    color: {
      color: "#FBF9F5",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Balkan Travel Insights",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  items: [
    {
      tag: {
        value: "CURATED",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      title: {
        value: "Decoding the Stećci",
        textColor: "#FFFFFF",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value: "Mythology of the medieval tombstones across the ancient high passes of Bosnia and Herzegovina.",
        textColor: "#E5E7EB",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      button: {
        label: "Read Article",
        url: "/stories/decoding-the-stecci",
        variant: "PRIMARY",
        style: "primary",
        rounded: "full",
        backgroundColor: "#182D09",
        backgroundOpacity: 100,
        textColor: "#ffffff",
        textOpacity: 100,
        hoverBackgroundColor: "#f3f4f6",
        hoverTextColor: "#000000",
        target: "_self",
        showIcon: true,
      },
      isFeatured: true,
    },
    {
      tag: {
        value: "HERITAGE",
        textColor: "#C5A880",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      title: {
        value: "The Salt Merchants of Ston",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value: "Tracking the white gold of the Adriatic along the ancient fortified walls of Pelješac peninsula.",
        textColor: "#4B5563",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      button: {
        label: "Read Article",
        url: "/stories/salt-merchants-of-ston",
        variant: "PRIMARY",
        style: "primary",
        rounded: "full",
        backgroundColor: "#182D09",
        backgroundOpacity: 100,
        textColor: "#ffffff",
        textOpacity: 100,
        hoverBackgroundColor: "#f3f4f6",
        hoverTextColor: "#000000",
        target: "_self",
        showIcon: true,
      },
      isFeatured: false,
    },
  ],
  buttons: [
    {
      label: "View All Stories",
      url: "/stories",
      variant: "PRIMARY",
      style: "primary",
      rounded: "full",
      backgroundColor: "#182D09",
      backgroundOpacity: 100,
      textColor: "#ffffff",
      textOpacity: 100,
      hoverBackgroundColor: "#f3f4f6",
      hoverTextColor: "#000000",
      target: "_self",
      showIcon: true,
    },
  ],
}
