export const emptyStoriesCmsHero = {
  breadcrumb: {
    value: "MIRA STORIES",
    textColor: "#E5E7EB",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Perspectives, History & Cultural Narratives",
    textColor: "#ffffff",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value: "",
    textColor: "#E5E7EB",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value: "A curated collection of stories, essays, and editorial pieces offering deep insight into the soul of the Balkans.",
    textColor: "#E5E7EB",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  isCenter: false,
  buttons: [],
  backgroundMultimedia: {
    show: "image",
    color: {
      color: "#182D09",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "MIRA Stories Editorial",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 35,
    },
    video: {
      url: "",
      alt: "",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      autoplay: true,
      loop: true,
      muted: true,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
  },
}
