export const emptyHero = {
  breadcrumb: {
    value: "",
    textColor: "#d29393",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Extraordinary Journeys,\nThoughtfully Designed",
    textColor: "#FFFFFF",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value:
      "Private, tailor-made journeys across the Balkans, combining distinctive stays, meaningful experiences and unhurried travel.",
    textColor: "#E5E7EB",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value: "",
    textColor: "#F3F4F6",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  isCenter: false,
  buttons: [
    {
      label: "Explore our Journeys",
      url: "#journeys",
      variant: "PRIMARY",
      style: "primary",
      rounded: "none",
      backgroundColor: "#ffffff",
      backgroundOpacity: 100,
      textColor: "#000000",
      textOpacity: 100,
      hoverBackgroundColor: "#f3f4f6",
      hoverTextColor: "#000000",
      target: "_self",
      showIcon: true,
    },
  ],
  backgroundMultimedia: {
    show: "video",
    color: {
      color: "#171717",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "mira hero",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Cinematic Aerial View",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
