export const emptyContactInfo = {
  items: [
    {
      label: {
        value: "EMAIL",
        textColor: "#6B7280",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      subtitle: {
        value: "hello@miratravel.com",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      button: {
        label: "Email Us",
        url: "mailto:hello@miratravel.com",
        variant: "PRIMARY",
        style: "primary",
        rounded: "none",
        backgroundColor: "#182D09",
        backgroundOpacity: 100,
        textColor: "#ffffff",
        textOpacity: 100,
        hoverBackgroundColor: "#f3f4f6",
        hoverTextColor: "#000000",
        target: "_self",
        showIcon: true,
      },
      multimedia: {
        show: "image",
        color: {
          color: "#E5E7EB",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
        image: {
          url: "",
          alt: "Email icon",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: "Email icon",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          autoplay: true,
          loop: true,
          muted: true,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
      },
    },
    {
      label: {
        value: "WHATSAPP",
        textColor: "#6B7280",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      subtitle: {
        value: "+355 69 123 4567",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      button: {
        label: "Chat on WhatsApp",
        url: "https://wa.me/355691234567",
        variant: "PRIMARY",
        style: "primary",
        rounded: "none",
        backgroundColor: "#182D09",
        backgroundOpacity: 100,
        textColor: "#ffffff",
        textOpacity: 100,
        hoverBackgroundColor: "#f3f4f6",
        hoverTextColor: "#000000",
        target: "_blank",
        showIcon: true,
      },
      multimedia: {
        show: "image",
        color: {
          color: "#E5E7EB",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
        image: {
          url: "",
          alt: "WhatsApp icon",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: "WhatsApp icon",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          autoplay: true,
          loop: true,
          muted: true,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
      },
    },
    {
      label: {
        value: "RESPONSE TIME",
        textColor: "#6B7280",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      subtitle: {
        value: "We typically respond within 24 hours.",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      button: {
        label: "",
        url: "",
        variant: "PRIMARY",
        style: "primary",
        rounded: "none",
        backgroundColor: "#182D09",
        backgroundOpacity: 100,
        textColor: "#ffffff",
        textOpacity: 100,
        hoverBackgroundColor: "#f3f4f6",
        hoverTextColor: "#000000",
        target: "_self",
        showIcon: true,
      },
      multimedia: {
        show: "image",
        color: {
          color: "#E5E7EB",
          opacity: 100,
          width: "100%",
          height: "100%",
          aspectRatio: "auto",
        },
        image: {
          url: "",
          alt: "Response time icon",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
        video: {
          url: "",
          alt: "Response time icon",
          opacity: 100,
          overlayColor: "#000000",
          overlayOpacity: 0,
          autoplay: true,
          loop: true,
          muted: true,
          width: "100%",
          height: "auto",
          aspectRatio: "auto",
          fit: "cover",
        },
      },
    },
  ],
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FFFFFF",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Contact info section background image",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Contact info section background video",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}

