/* =====================================================
   LOCATION — DEFAULT / INITIAL DRAFT (EUROPE)
   Default data loaded when creating a new location.
   Image & Video URLs are left blank so user doesn't have to delete them.
===================================================== */

import type { LocationData } from "../locationTypes"

export const emptyLocation: LocationData = {
  name: "Europe",
  type: "CONTINENT",
  parentId: null,

  hero: {
    breadcrumb: {
      value: "CONTINENTS / EUROPE",
      textColor: "#d29393",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "Unveil the Soul of Europe",
      textColor: "#FFFFFF",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    subtitle: {
      value: "From Ancient Empires to Wild Alpine Horizons",
      textColor: "#E5E7EB",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value: "Immerse yourself in timeless cultural heritage, majestic mountain passes, sun-drenched Mediterranean shores, and secluded storybook villages crafted for discerning explorers.",
      textColor: "#F3F4F6",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    isCenter: false,
    buttons: [
      {
        label: "Explore European Journeys",
        url: "/journeys?continent=europe",
        style: "primary",
        variant: "PRIMARY",
        textColor: "#000000",
        backgroundColor: "#ffffff",
      },
    ],
    backgroundMultimedia: {
      show: "video",
      image: {
        url: "/videos/des-thumb.png",
        alt: "Panoramic European Alpine Landscape",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 45,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "/videos/des-hero.mp4",
        alt: "Cinematic Aerial View of Europe",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 45,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      color: {
        color: "#171717",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
    },
  },

  essence: {
    label: {
      value: "THE ESSENCE OF EUROPE",
      textColor: "#af6348",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "A tapestry of living history, untamed wilderness, and timeless elegance",
      textColor: "#182d09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    paragraphs: {
      value:
        "Europe is an extraordinary mosaic where centuries of civilization meet pristine natural wonder. From the snow-capped summits of the Alps and the sun-drenched coves of the Mediterranean to fairy-tale medieval towns and ancient pine forests, every corner holds a distinct chapter waiting to be discovered.\n\nHere, travel transcends the ordinary. Wander through cobblestone alleyways that have witnessed millennia of history, savour world-renowned culinary heritage crafted by generational artisans, and lose yourself in landscapes that have inspired poets, artists, and explorers across generations.\n\nWhether navigating remote coastal paths or uncovering secluded mountain refuges far from the beaten track, Europe rewards curious minds with profound intimacy and indelible memories.",
      textColor: "#565e69",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    quote: {
      value:
        "To travel through Europe is to witness the living poetry of the ancient world reimagined for the modern spirit.",
      textColor: "#1A1209",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    stat: {
      statValue: {
        value: "50+",
        textColor: "#ffffff",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      statLabel: {
        value: "Countries & Sovereign Territories",
        textColor: "#ffffff",
        textOpacity: 0.75,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      statBadgeBg: "#B86B3A",
    },
    imageMultimedia: {
      show: "image",
      image: {
        url: "",
        alt: "The Essence of Europe — Landscapes & Heritage",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "The Essence of Europe video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
        fit: "cover",
      },
      color: {
        color: "#EDE7D8",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
    },
    backgroundMultimedia: {
      show: "color",
      image: {
        url: "",
        alt: "Europe essence background pattern",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "Europe essence background video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      color: {
        color: "#FFF8F2",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
    },
  },

  highlights: {
    label: {
      value: "SEASONAL HIGHLIGHTS",
      textColor: "#af6348",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "Regions of Europe",
      textColor: "#182d09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value:
        "A selection of destinations currently resonating with our most discerning travelers.",
      textColor: "#565e69",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    items: [],
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#FFF8F2",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Highlights background",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "Highlights background video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
  },

  regionExperiences: {
    label: {
      value: "EXPLORE ALBANIA",
      textColor: "#af6348",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "Four Regions. Four Different Experiences.",
      textColor: "#182d09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#f5f5f5",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Region Experiences background",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "Region Experiences background video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    items: [],
  },

  geoData: {
    title: {
      value: "Interactive Map",
      textColor: "#0a0a0a",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value:
        "Spin the globe, then zoom into the destination to explore our properties.",
      textColor: "#565e69",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#FFF8F2",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Map background",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "Map background video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    geo: {
      latitude: 41.1533,
      longitude: 20.1683,
      mapZoom: 4,
      pitch: 0,
      bearing: 0,
      timezone: "UTC+1 (CET)",
      area: {
        value: 28748,
        unit: "km²",
      },
    },
    showChildren: true,
  },

  travelInsight: {
    label: {
      value: "TRAVEL INSIGHTS",
      textColor: "#d29393",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "Everything you need to know before you go",
      textColor: "#e5e5e5",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    featuredMultimedia: {
      show: "image",
      image: {
        url: "",
        alt: "Featured Local Guide Article",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      color: {
        color: "#182d09",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#182d09",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Travel Insights background",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "Travel Insights background video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    articles: [],
  },

  signatureExperiences: {
    label: {
      value: "Signature Experiences",
      textColor: "#af6348",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "Five ways to fall in love with Europe",
      textColor: "#182d09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value:
        "Immerse yourself in authentic cultural encounters, historic marvels, and breathtaking wilderness adventures crafted exclusively for discerning travelers.",
      textColor: "#565e69",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#FFFFFF",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Signature experiences background",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "Signature experiences background video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    items: [],
  },

  faq: {
    title: {
      value: "Frequently Asked Questions",
      textColor: "#182d09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    imageMultimedia: {
      show: "image",
      image: {
        url: "/images/faq.jpg",
        alt: "Frequently Asked Questions",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "100%",
        aspectRatio: "1:1",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      color: {
        color: "#EDE7D8",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "1:1",
      },
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#F8F5EE",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "FAQ Background Pattern",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "FAQ Background Video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    items: [
      {
        question: {
          value: "What is the best time of year to visit Albania and the Balkans?",
          textColor: "#182d09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        answer: {
          value: "Spring (April–June) and Autumn (September–October) offer ideal weather with pleasant temperatures, blooming scenery, and fewer crowds.",
          textColor: "#565e69",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
      {
        question: {
          value: "Do I need a visa to travel to Albania?",
          textColor: "#182d09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        answer: {
          value: "Visa requirements depend on your nationality. Many travelers from EU, US, UK, and Commonwealth countries can enter visa-free for up to 90 days. Check diplomatic guidelines prior to travel.",
          textColor: "#565e69",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
      {
        question: {
          value: "How do we travel between mountains, UNESCO towns, and the coast?",
          textColor: "#182d09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        answer: {
          value: "We arrange private luxury chauffeured vehicles, private coastal boat transfers, and scenic helicopter flights for comfortable, scenic transitions.",
          textColor: "#565e69",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
      {
        question: {
          value: "Is Albania safe for solo travelers, couples, and families?",
          textColor: "#182d09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        answer: {
          value: "Albania is renowned for its hospitality (Besa) and has very low crime rates. Our 24/7 dedicated travel concierge is always on hand throughout your journey.",
          textColor: "#565e69",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
      {
        question: {
          value: "Can dietary preferences and boutique accommodations be tailored?",
          textColor: "#182d09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        answer: {
          value: "Yes. Every itinerary is fully personalized with handpicked heritage boutique stays and dining customized for vegetarian, vegan, gluten-free, and halal preferences.",
          textColor: "#565e69",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
      {
        question: {
          value: "How does Mira design and support our personalized journey?",
          textColor: "#182d09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        answer: {
          value: "From 1-on-1 itinerary planning to on-the-ground VIP assistance, expert storytelling guides, and luxury transit, we ensure every moment is extraordinary.",
          textColor: "#565e69",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
    ],
  },

  cta: {
    title: {
      value: "Didn't find your perfect journey?",
      textColor: "#182d09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value:
        "Our collection is carefully designed but every travel is different.\nIf you'd like something more personal, we'd love to create it together.",
      textColor: "#565e69",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    buttons: [
      {
        label: "Plan a tailor-made journey",
        url: "/contact",
        style: "primary",
        variant: "PRIMARY",
        backgroundColor: "#af6348",
        textColor: "#ffffff",
      },
    ],
    imageMultimedia: {
      show: "image",
      image: {
        url: "/images/cta.png",
        alt: "CTA Motif",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
        fit: "contain",
      },
      video: {
        url: "",
        alt: "",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      color: {
        color: "#EDE7D8",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#EDE7D8",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "CTA Background Pattern",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "CTA Background Video",
        autoplay: true,
        loop: true,
        muted: true,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
  },

  metadata: {
    seo: {
      title: "Europe Travel Guide | Historic Wonders, Alpine Peaks & Coastal Escapes",
      description:
        "Explore Europe with Mira Travel. Discover bespoke luxury journeys, rich cultural landmarks, pristine nature, and curated accommodations.",
      keywords: ["Europe", "Luxury Travel", "European Holidays", "Custom Itineraries", "Mira Travel"],
      canonicalUrl: "/destinations/europe",
      robots: {
        index: true,
        follow: true,
      },
    },
  },
}



