export const emptyTravelInsights = {
  label: {
    value: "TRAVEL INSIGHTS",
    textColor: "#d29393",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Everything you need to know before you go",
    textColor: "#e5e5e5",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  featuredMultimedia: {
    show: "image",
    image: {
      url: "",
      alt: "Featured Local Guide Article",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    color: {
      color: "#182d09",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#182d09",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Travel Insights background",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Travel Insights background video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  articles: [],
}
