import type { Story, ArticleBlock } from "../storyTypes"

export const DEFAULT_STORY_STYLES = {
  heroColor: "#171717",
  terracotta: "#af6348",
  heroImage: "",
}

export const emptyStory: Story = {
  id: "",
  title: "Stories from the Balkans",
  slug: "stories-from-the-balkans",
  category: "Culture & Heritage",
  categories: ["Culture & Heritage"],
  description: "There is something about the Balkans that resists quick travel. It unfolds slowly through mountain passes and weathered villages.",
  readTime: "5 min read",
  templateType: "long-story",
  image: "",
  detail: {
    breadcrumb: {
      value: "Stories",
      textColor: "#d29393",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "Stories from the Balkans",
      textColor: "#FFFFFF",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    subtitle: {
      value: "There is something about the Balkans that resists quick travel. It unfolds slowly through mountain passes and weathered villages.",
      textColor: "#E5E7EB",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value: "",
      textColor: "#F3F4F6",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    isCenter: false,
    buttons: [
      {
        label: "Start Your Journey",
        url: "#journeys",
        variant: "PRIMARY",
        style: "primary",
        rounded: "none",
        backgroundColor: "#ffffff",
        backgroundOpacity: 100,
        textColor: "#000000",
        textOpacity: 100,
        hoverBackgroundColor: "#f3f4f6",
        hoverTextColor: "#000000",
        target: "_self",
        showIcon: true,
      },
    ],
    backgroundMultimedia: {
      show: "image",
      color: {
        color: "#171717",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Stories from the Balkans",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 45,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "Cinematic Aerial View",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 45,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    titleStyle: { textColor: "#FFFFFF" },
    descriptionStyle: { textColor: "#FBF9F5" },
    readTimeStyle: { textColor: "#FDE68A" },
    author: "MIRA Editorial",
    authorStyle: { textColor: "#FFFFFF" },
    authorTitle: "Curator & Travel Writer",
    authorTitleStyle: { textColor: "rgba(255, 255, 255, 0.75)" },
    tagPlace: "",
    tagTheme: "Culture",
    tagLens: "Tradition",
    destinationPlace: "",
    journeyIds: [],
    manualRelatedStoryIds: [],
    blocks: [
      {
        id: "b1",
        type: "paragraph",
        text: "There is something about the Balkans that resists quick travel. The region does not announce itself through mega-cities or crammed expressways. Instead, it unfolds slowly—through silent mountain passes, weathered stone villages, and conversations that linger over strong coffee.",
      },
      {
        id: "b2",
        type: "image",
        url: "",
        caption: "Panoramic view of authentic stone architecture in Mostar",
        multimedia: {
          type: "image",
          url: "",
          alt: "Mostar stone architecture",
        },
      },
      {
        id: "b3",
        type: "spotlight",
        title: "The Albanian Riviera",
        text: "The Albanian Riviera offers dramatic coastal views where steep mountains plunge directly into crystal-clear turquoise waters. This is a landscape born of contrasting elements, raw, wild and unbothered.",
        url: "",
        layout: "image-left",
        textStyle: { textColor: DEFAULT_STORY_STYLES.terracotta },
        multimedia: {
          type: "image",
          url: "",
          alt: "The Albanian Riviera",
        },
      },
      {
        id: "b4",
        type: "quote",
        text: "The Balkans are not discovered quickly. They unfold slowly, revealing themselves to those who take the time to listen.",
        textStyle: { textColor: DEFAULT_STORY_STYLES.terracotta },
      },
    ],
  },
}
