export const emptyEssence = {
  label: {
    value: "THE ESSENCE OF EUROPE",
    textColor: "#af6348",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "A tapestry of living history, untamed wilderness, and timeless elegance",
    textColor: "#182d09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  paragraphs: {
    value:
      "Europe is an extraordinary mosaic where centuries of civilization meet pristine natural wonder. From the snow-capped summits of the Alps and the sun-drenched coves of the Mediterranean to fairy-tale medieval towns and ancient pine forests, every corner holds a distinct chapter waiting to be discovered.\n\nHere, travel transcends the ordinary. Wander through cobblestone alleyways that have witnessed millennia of history, savour world-renowned culinary heritage crafted by generational artisans, and lose yourself in landscapes that have inspired poets, artists, and explorers across generations.\n\nWhether navigating remote coastal paths or uncovering secluded mountain refuges far from the beaten track, Europe rewards curious minds with profound intimacy and indelible memories.",
    textColor: "#565e69",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  quote: {
    value:
      "To travel through Europe is to witness the living poetry of the ancient world reimagined for the modern spirit.",
    textColor: "#1A1209",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  stat: {
    statValue: {
      value: "50+",
      textColor: "#ffffff",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    statLabel: {
      value: "Countries & Sovereign Territories",
      textColor: "#ffffff",
      textOpacity: 0.75,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    statBadgeBg: "#B86B3A",
  },
  imageMultimedia: {
    show: "image",
    image: {
      url: "",
      alt: "The Essence of Europe — Landscapes & Heritage",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "The Essence of Europe video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
      fit: "cover",
    },
    color: {
      color: "#EDE7D8",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
  },
  backgroundMultimedia: {
    show: "color",
    image: {
      url: "",
      alt: "Europe essence background pattern",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Europe essence background video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    color: {
      color: "#FFF8F2",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
  },
}
