export const emptyRegionalKnowledge = {
  eyebrow: {
    value: "REGIONAL KNOWLEDGE",
    textColor: "#B86B3A",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Deeply rooted in the Balkans.",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "Lorem ipsum dolor sit amet consectetur. Fusce egestas risus placerat ornare vitae ut. Est fermentum amet duis imperdiet fames. Vestibulum amet quis nisl risus mattis. Est amet sed facilisis molestie. Augue eget elementum habitant nulla fermentum. Tortor interdum rhoncus et justo cras. Elit pellentesque nisi nulla habitasse dui ipsum adipiscing.\n\nLorem ipsum dolor sit amet consectetur. Nisi ligula consectetur odio urna. Cras vitae amet aenean feugiat. Mattis lorem mauris hendrerit adipiscing tempor posuere amet lacus. Integer potenti diam ullamcorper integer massa urna elementum.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  secondaryDescription: {
    value:
      "From remote mountain villages and coastal hideaways to historic cities and lesser-known cultural regions, we focus on places that retain a strong sense of identity and authenticity.\n\nOver the years, we have built long-standing relationships with local guides, boutique properties, drivers, artisans, and hospitality partners throughout the region. These connections allow us to create journeys that feel both refined and deeply personal.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  multimedia1: {
    show: "image",
    color: {
      color: "#E5E7EB",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Deeply rooted in the Balkans",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  multimedia2: {
    show: "image",
    color: {
      color: "#E5E7EB",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Balkan cultural heritage",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FAF7F2",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
