export const emptyJourneyCmsHero = {
  breadcrumb: {
    value: "EXPLORE JOURNEYS",
    textColor: "#E5E7EB",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "Tailored Balkan Journeys Crafted for Discerning Travelers",
    textColor: "#ffffff",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  subtitle: {
    value: "",
    textColor: "#E5E7EB",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value: "Discover handcrafted itineraries that combine cultural depth, boutique luxury, and unforgettable landscapes across the Balkans.",
    textColor: "#E5E7EB",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  isCenter: false,
  buttons: [],
  backgroundMultimedia: {
    show: "image",
    color: {
      color: "#182D09",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1920&q=80",
      alt: "Tailored Balkan Journeys",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 30,
    },
    video: {
      url: "",
      alt: "",
      fit: "cover",
      width: "100%",
      height: "auto",
      opacity: 100,
      autoplay: true,
      loop: true,
      muted: true,
      aspectRatio: "auto",
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
  },
}
