export const emptyGlance = {
  label: {
    value: "REGIONAL ORIENTATION",
    textColor: "#af6348",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "The Region at a Glance",
    textColor: "#182d09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value: "",
    textColor: "#565e69",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  items: [],
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FFFFFF",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Glance section background",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Glance section background video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
