export const emptyGeoData = {
  title: {
    value: "Interactive Map",
    textColor: "#0a0a0a",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "Spin the globe, then zoom into the destination to explore our properties.",
    textColor: "#565e69",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FFF8F2",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Map background",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Map background video",
      autoplay: true,
      loop: true,
      muted: true,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  geo: {
    latitude: 41.1533,
    longitude: 20.1683,
    mapZoom: 4,
    pitch: 0,
    bearing: 0,
    timezone: "UTC+1 (CET)",
    area: {
      value: 28748,
      unit: "km²",
    },
  },
  showChildren: true,
}
