export const emptyStandardItemIcon = {
  show: "image",
  color: {
    color: "#E5E7EB",
    opacity: 100,
    width: "100%",
    height: "100%",
    aspectRatio: "auto",
  },
  image: {
    url: "",
    alt: "Feature Icon",
    opacity: 100,
    overlayColor: "#000000",
    overlayOpacity: 0,
    width: "100%",
    height: "auto",
    aspectRatio: "auto",
    fit: "cover",
  },
  video: {
    url: "",
    alt: null,
    opacity: 100,
    overlayColor: "#000000",
    overlayOpacity: 0,
    autoplay: true,
    loop: true,
    muted: true,
    width: "100%",
    height: "auto",
    aspectRatio: "auto",
    fit: "cover",
  },
}

export const emptyStandardItem = {
  title: {
    value: "Thoughtful Pace",
    textColor: "#B86B3A",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  description: {
    value:
      "Lorem ipsum dolor sit amet consectetur. Non pretium id eu justo massa condimentum proin. Aliquam vitae tellus quis nulla et bibendum. Vulputate quis enim arcu congue.",
    textColor: "#4B5563",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  icon: emptyStandardItemIcon,
}

export const emptyStandard = {
  eyebrow: {
    value: "THE MIRA STANDARD",
    textColor: "#B86B3A",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  title: {
    value: "What defines every journey we create.",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  multimedia: {
    show: "image",
    color: {
      color: "#E5E7EB",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "The MIRA Standard of travel excellence",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
  items: [
    {
      title: {
        value: "Thoughtful Pace",
        textColor: "#B86B3A",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value:
          "Lorem ipsum dolor sit amet consectetur. Non pretium id eu justo massa condimentum proin. Aliquam vitae tellus quis nulla et bibendum. Vulputate quis enim arcu congue.",
        textColor: "#4B5563",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      icon: emptyStandardItemIcon,
    },
    {
      title: {
        value: "Distinctive Places",
        textColor: "#B86B3A",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value:
          "Lorem ipsum dolor sit amet consectetur. Non pretium id eu justo massa condimentum proin. Aliquam vitae tellus quis nulla et bibendum. Vulputate quis enim arcu congue.",
        textColor: "#4B5563",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      icon: emptyStandardItemIcon,
    },
    {
      title: {
        value: "Regional Depth",
        textColor: "#B86B3A",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value:
          "Lorem ipsum dolor sit amet consectetur. Non pretium id eu justo massa condimentum proin. Aliquam vitae tellus quis nulla et bibendum. Vulputate quis enim arcu congue.",
        textColor: "#4B5563",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      icon: emptyStandardItemIcon,
    },
    {
      title: {
        value: "Seamless Execution",
        textColor: "#B86B3A",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value:
          "Lorem ipsum dolor sit amet consectetur. Non pretium id eu justo massa condimentum proin. Aliquam vitae tellus quis nulla et bibendum. Vulputate quis enim arcu congue.",
        textColor: "#4B5563",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      icon: emptyStandardItemIcon,
    },
  ],
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FAF7F2",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: null,
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 0,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
