export const emptyProcess = {
  title: {
    value: "How The Process Works",
    textColor: "#182D09",
    textOpacity: 1,
    backgroundColor: null,
    backgroundOpacity: 1,
  },
  items: [
    {
      badge: "STEP 01",
      title: {
        value: "Share your travel ideas",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value: "Tell us about your dreams, preferred pace, and the experiences that move you.",
        textColor: "#4B5563",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
    },
    {
      badge: "STEP 02",
      title: {
        value: "We curate your journey",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value: "Our specialists draft a narrative itinerary that balances discovery with moments of rest.",
        textColor: "#4B5563",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
    },
    {
      badge: "STEP 03",
      title: {
        value: "Refine every detail together",
        textColor: "#182D09",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
      description: {
        value: "We iterate until the itinerary feels perfect, ensuring every stay and connection is seamless.",
        textColor: "#4B5563",
        textOpacity: 1,
        backgroundColor: null,
        backgroundOpacity: 1,
      },
    },
  ],
  backgroundMultimedia: {
    show: "color",
    color: {
      color: "#FFFFFF",
      opacity: 100,
      width: "100%",
      height: "100%",
      aspectRatio: "auto",
    },
    image: {
      url: "",
      alt: "Contact us hero image",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
    video: {
      url: "",
      alt: "Contact us hero video",
      opacity: 100,
      overlayColor: "#000000",
      overlayOpacity: 45,
      autoplay: true,
      loop: true,
      muted: true,
      width: "100%",
      height: "auto",
      aspectRatio: "auto",
      fit: "cover",
    },
  },
}
